#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034 # rc.common consumes these service variables.

USE_PROCD=1
START=91
STOP=09

CONFIG_FILE="/tmp/ipv6-test-dhcpv6.conf"

start_service() {
	[ -s "$CONFIG_FILE" ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/dnsmasq \
		--keep-in-foreground \
		--conf-file="$CONFIG_FILE" \
		--pid-file=/var/run/ipv6-test-dhcpv6.pid
	procd_set_param file "$CONFIG_FILE"
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger ipv6test
}
