include $(TOPDIR)/rules.mk

LUCI_TITLE:=WiFi Test Driver Manager
LUCI_DEPENDS:=+luci-app-wifi-test
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
