include $(TOPDIR)/rules.mk

LUCI_TITLE:=WiFi Test Suite
LUCI_DEPENDS:=+test-driver-base
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
